//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeployTrackerMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteBody
    {
        public int id { get; set; }
        public Nullable<int> noteID { get; set; }
        public string body { get; set; }
    
        public virtual Note Note { get; set; }
    }
}
