//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeployTrackerMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComment
    {
        public Nullable<int> depID { get; set; }
        public int comID { get; set; }
        public string comBody { get; set; }
        public DateTimeOffset comDateTime { get; set; }
        public string comUser { get; set; }
        
    }
}
