//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeployTrackerMVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNote
    {
        public int noteID { get; set; }
        public string noteBody { get; set; }
        public Nullable<System.DateTimeOffset> noteDateTime { get; set; }
    }
}
